name: Publish Docker image

on:
  push:
    branches:
      - build
      - release
jobs:
  build-client-and-publish-to-registery:
    name: Push Docker Client image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          github-token: ${{ secrets.TOKEN }}
          images: ${{secrets.DOCKER_USERNAME}}/cbnclient

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ secrets.DOCKER_USERNAME }}/cbnclient:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-server-and-publish-to-registery:
    name: Push Docker Server image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          github-token: ${{ secrets.TOKEN }}
          images: ${{secrets.DOCKER_USERNAME}}/cbnserver

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ secrets.DOCKER_USERNAME}}/hubhubserver:latest
          labels: ${{ steps.meta.outputs.labels }}
